# -*- coding: utf-8 -*-
"""AI & BLOCKCHAIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgUFNBFmzN-D2rie1Sx2ebSTkgrDLdJH
"""

import numpy as np
import pandas as pd
df = pd.read_csv('/content/diabetes.csv')
df

df.head()

df.tail()

df.columns

df.shape

"""for checking the type"""

df.dtypes

#for checking missing values
df.isna().sum()

extract all columns except the last one from a DataFrame and store them as a NumPy array.
x=df.iloc[:,:-1].values
x

y=df.iloc[:,-1].values
y

#Splitting into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=42)
x_train

x_test

x_test

y_test

#normalisation
#standardScalar
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(x_train)
x_train_nor=ss.transform(x_train)
x_test_nor=ss.transform(x_test)
x_train_nor

x_test_nor

#model creation
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier(n_neighbors=7)
knn1.fit(x_train_nor,y_train)
Y_pred=knn1.predict(x_test_nor)
Y_pred

y_test

#to evaluate performance
from sklearn.metrics import classification_report
print(classification_report(Y_pred,y_test))

#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,Y_pred)

pred=knn1.predict(ss.transform([[5,130,72,35,0,33.6,0.627,50]]))
pred